databases:
  - name: cars-database
    databaseName: cars_database
    user: cars_database_user

services:
  - type: web
    name: carsHub
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cars_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
